import { computeAcademicMetric } from "@/lib/academic-intelligence";
import type { ReportSubjectRow, SchoolIdentity, Student } from "@/lib/types";

export const demoStudents: Student[] = [
  { id: "stu-001", fullName: "Aïcha Koné", className: "6e A", average: 13.4, attendanceRate: 94 },
  { id: "stu-002", fullName: "Moussa Traoré", className: "6e A", average: 9.2, attendanceRate: 76 },
  { id: "stu-003", fullName: "Fatou Diallo", className: "5e B", average: 15.1, attendanceRate: 97 },
];

export const demoMetrics = demoStudents.map((s, idx) =>
  computeAcademicMetric({
    studentId: s.id,
    averageScore: s.average,
    attendanceRate: s.attendanceRate,
    previousAverageScore: s.average - (idx === 1 ? -0.8 : 0.4),
  }),
);

export const demoSchool: SchoolIdentity = {
  name: "Elima Academy",
  address: "Cocody Riviera, Rue des Écoles",
  city: "Abidjan",
  country: "Côte d’Ivoire",
  phone: "+225 01 23 45 67 89",
  email: "contact@elima.com",
  site: "elima.tech",
};

export const demoReportRows: Record<string, ReportSubjectRow[]> = {
  "stu-001": [
    {
      subject: "Français",
      teacher: "Mme Konan",
      coefficient: 3,
      termScores: { "Trimestre 1": 14.5 },
      yearScore: 14.5,
      appreciation: "Très bon trimestre. Efforts réguliers, continue ainsi.",
    },
    {
      subject: "Mathématiques",
      teacher: "M. Traoré",
      coefficient: 4,
      termScores: { "Trimestre 1": 12.0 },
      yearScore: 12.0,
      appreciation: "Bon niveau. Attention aux erreurs d’inattention.",
    },
    {
      subject: "Histoire-Géographie",
      teacher: "Mme Diallo",
      coefficient: 2,
      termScores: { "Trimestre 1": 13.0 },
      yearScore: 13.0,
      appreciation: "Travail sérieux et participation pertinente.",
    },
    {
      subject: "Anglais",
      teacher: "M. Kouamé",
      coefficient: 2,
      termScores: { "Trimestre 1": 15.0 },
      yearScore: 15.0,
      appreciation: "Très bon ensemble. Bonne progression à l’oral.",
    },
    {
      subject: "Sciences physiques",
      teacher: "M. Touré",
      coefficient: 2,
      termScores: { "Trimestre 1": 12.5 },
      yearScore: 12.5,
      appreciation: "Résultats corrects. Revoir les exercices de base.",
    },
    {
      subject: "SVT",
      teacher: "Mme N’Guessan",
      coefficient: 2,
      termScores: { "Trimestre 1": 13.8 },
      yearScore: 13.8,
      appreciation: "Bon trimestre. Participation en progrès.",
    },
    {
      subject: "Technologie",
      teacher: "M. Diabaté",
      coefficient: 1,
      termScores: { "Trimestre 1": 16.0 },
      yearScore: 16.0,
      appreciation: "Très à l’aise. Bon esprit logique.",
    },
    {
      subject: "Espagnol",
      teacher: "Mme Garcia",
      coefficient: 1,
      termScores: { "Trimestre 1": 14.2 },
      yearScore: 14.2,
      appreciation: "Bon trimestre. Continuer l’effort sur le vocabulaire.",
    },
    {
      subject: "EPS",
      teacher: "M. Koffi",
      coefficient: 1,
      termScores: { "Trimestre 1": 17.0 },
      yearScore: 17.0,
      appreciation: "Très bon engagement et esprit d’équipe.",
    },
  ],
  "stu-002": [
    {
      subject: "Français",
      teacher: "Mme Konan",
      coefficient: 3,
      termScores: { "Trimestre 1": 9.0 },
      yearScore: 9.0,
      appreciation: "Résultats insuffisants. Revoir les bases et travailler la méthode.",
    },
    {
      subject: "Mathématiques",
      teacher: "M. Traoré",
      coefficient: 4,
      termScores: { "Trimestre 1": 8.5 },
      yearScore: 8.5,
      appreciation: "Difficultés persistantes. Exercices réguliers indispensables.",
    },
    {
      subject: "Histoire-Géographie",
      teacher: "Mme Diallo",
      coefficient: 2,
      termScores: { "Trimestre 1": 10.0 },
      yearScore: 10.0,
      appreciation: "Peut mieux faire. Apprendre le cours et soigner les devoirs.",
    },
    {
      subject: "Anglais",
      teacher: "M. Kouamé",
      coefficient: 2,
      termScores: { "Trimestre 1": 9.2 },
      yearScore: 9.2,
      appreciation: "Efforts à intensifier. Participer davantage en classe.",
    },
    {
      subject: "Sciences physiques",
      teacher: "M. Touré",
      coefficient: 2,
      termScores: { "Trimestre 1": 9.0 },
      yearScore: 9.0,
      appreciation: "Résultats faibles. Revoir les notions fondamentales.",
    },
    {
      subject: "SVT",
      teacher: "Mme N’Guessan",
      coefficient: 2,
      termScores: { "Trimestre 1": 9.8 },
      yearScore: 9.8,
      appreciation: "Résultats fragiles. Revoir le cours et faire des exercices.",
    },
    {
      subject: "Technologie",
      teacher: "M. Diabaté",
      coefficient: 1,
      termScores: { "Trimestre 1": 10.5 },
      yearScore: 10.5,
      appreciation: "Peut mieux faire. Être plus régulier.",
    },
    {
      subject: "Allemand",
      teacher: "Mme Schmidt",
      coefficient: 1,
      termScores: { "Trimestre 1": 9.5 },
      yearScore: 9.5,
      appreciation: "Vocabulaire à renforcer. Refaire les leçons.",
    },
    {
      subject: "EPS",
      teacher: "M. Koffi",
      coefficient: 1,
      termScores: { "Trimestre 1": 14.0 },
      yearScore: 14.0,
      appreciation: "Bon investissement. Continuer.",
    },
  ],
  "stu-003": [
    {
      subject: "Français",
      teacher: "Mme Konan",
      coefficient: 3,
      termScores: { "Trimestre 1": 16.0 },
      yearScore: 16.0,
      appreciation: "Excellent trimestre, travail de qualité.",
    },
    {
      subject: "Mathématiques",
      teacher: "M. Traoré",
      coefficient: 4,
      termScores: { "Trimestre 1": 17.5 },
      yearScore: 17.5,
      appreciation: "Très solide. Rigueur et méthode remarquables.",
    },
    {
      subject: "Histoire-Géographie",
      teacher: "Mme Diallo",
      coefficient: 2,
      termScores: { "Trimestre 1": 14.5 },
      yearScore: 14.5,
      appreciation: "Très bon ensemble. Bon esprit d’analyse.",
    },
    {
      subject: "Anglais",
      teacher: "M. Kouamé",
      coefficient: 2,
      termScores: { "Trimestre 1": 16.2 },
      yearScore: 16.2,
      appreciation: "Très bon niveau. Continue à enrichir le vocabulaire.",
    },
    {
      subject: "Sciences physiques",
      teacher: "M. Touré",
      coefficient: 2,
      termScores: { "Trimestre 1": 15.0 },
      yearScore: 15.0,
      appreciation: "Très bon trimestre. Démarche scientifique solide.",
    },
    {
      subject: "SVT",
      teacher: "Mme N’Guessan",
      coefficient: 2,
      termScores: { "Trimestre 1": 15.8 },
      yearScore: 15.8,
      appreciation: "Excellent trimestre. Travail sérieux.",
    },
    {
      subject: "Technologie",
      teacher: "M. Diabaté",
      coefficient: 1,
      termScores: { "Trimestre 1": 18.0 },
      yearScore: 18.0,
      appreciation: "Excellent. Très autonome.",
    },
    {
      subject: "Espagnol",
      teacher: "Mme Garcia",
      coefficient: 1,
      termScores: { "Trimestre 1": 15.0 },
      yearScore: 15.0,
      appreciation: "Très bon ensemble. Bonne prononciation.",
    },
    {
      subject: "EPS",
      teacher: "M. Koffi",
      coefficient: 1,
      termScores: { "Trimestre 1": 18.5 },
      yearScore: 18.5,
      appreciation: "Excellent engagement. Très bonne progression.",
    },
  ],
};
