export const API_ENDPOINTS = [
  "account-delete",
  "activate-school",
  "auth-password-reset",
  "auth-verification-check",
  "auth-verification-request",
  "elima-password-login",
  "elima-profile",
  "elima-signup",
  "identity-bridge",
  "learning",
  "registration-request",
  "revision-generate",
  "revision-document-analyze",
  "revision-document-delete",
];

export const REVISION_API_ENDPOINTS = [
  "account-delete",
  "identity-bridge",
  "elima-profile",
  "elima-password-login",
  "elima-signup",
  "auth-verification-check",
  "auth-verification-request",
  "auth-password-reset",
  "learning",
  "revision-generate",
  "revision-document-analyze",
  "revision-document-delete",
];
