import { useEffect, useState } from "react";
import { BellRing, CalendarDays, MapPin } from "lucide-react";
import { enableCourseNotifications, notifyUpcomingCourses } from "@/services/notificationService";
import type { TimetableEvent } from "@/types/school";

export function TimetableCard({ events, title = "Prochains cours" }: { events: TimetableEvent[]; title?: string }) {
  const [permission, setPermission] = useState<NotificationPermission | "unsupported">("Notification" in window ? Notification.permission : "unsupported");
  useEffect(() => { notifyUpcomingCourses(events); }, [events, permission]);
  return <section><div className="mb-3 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" /><h2 className="font-title text-lg font-semibold text-accent">{title}</h2></div>{permission === "default" ? <button type="button" onClick={async () => setPermission(await enableCourseNotifications())} className="flex items-center gap-1 text-xs font-semibold text-primary"><BellRing className="h-4 w-4" />Activer les rappels</button> : null}</div><div className="overflow-hidden rounded-3xl bg-white shadow-sm">{events.length ? events.slice(0, 4).map((event, index) => { const start = new Date(event.startsAt); const end = new Date(event.endsAt); const tomorrow = start.toDateString() !== new Date().toDateString(); return <div key={event.id} className={`flex items-center gap-3 p-4 ${index ? "border-t border-gray-100" : ""}`}><div className="w-16 shrink-0 text-center"><p className="text-xs font-semibold uppercase text-primary">{tomorrow ? "Demain" : start.toLocaleDateString("fr-FR", { weekday: "short" })}</p><p className="text-sm font-bold text-accent">{start.toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" })}</p></div><div className="min-w-0 flex-1"><p className="truncate font-semibold text-accent">{event.subject}</p><p className="truncate text-xs text-gray-500">{event.className} · jusqu’à {end.toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" })}</p></div>{event.room ? <span className="flex items-center gap-1 text-xs text-gray-400"><MapPin className="h-3.5 w-3.5" />{event.room}</span> : null}</div>; }) : <p className="p-5 text-sm text-gray-500">Aucun cours planifié aujourd’hui ou demain.</p>}</div></section>;
}
