import { Building2, ExternalLink, LogOut, ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { AppHeader } from "@/components/common/AppHeader";
import { ElimaLogo } from "@/components/common/ElimaLogo";
import { PageContainer } from "@/components/layout/PageContainer";
import { useAuth } from "@/features/auth/AuthProvider";
import { getPlanLabel } from "@/services/gatingService";
import { openWebPath } from "@/services/webLinkService";
import { getRoleLabel } from "@/types/roles";

export function AccountPage() {
  const { profile, signOut } = useAuth(); const navigate = useNavigate();
  return <PageContainer><AppHeader title="Mon compte" subtitle="Identité, établissement et sécurité" /><section className="overflow-hidden rounded-[2rem] bg-white shadow-sm"><div className="h-24 bg-[#173f31]" /><div className="px-5 pb-6"><div className="-mt-9 flex items-end gap-4">{profile.schoolLogoUrl ? <img src={profile.schoolLogoUrl} alt="" className="h-20 w-20 rounded-3xl border-4 border-white bg-white object-contain p-1 shadow-sm" /> : <span className="flex h-20 w-20 items-center justify-center rounded-3xl border-4 border-white bg-primary text-2xl font-bold text-white">{profile.schoolName?.charAt(0) ?? "E"}</span>}<div className="pb-1"><h2 className="font-title text-xl font-semibold text-accent">{profile.fullName}</h2><p className="text-sm text-gray-500">{getRoleLabel(profile.role)}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-gray-50 p-4"><Building2 className="h-5 w-5 text-primary" /><p className="mt-2 text-xs text-gray-400">Établissement</p><p className="font-semibold text-accent">{profile.schoolName ?? "Non renseigné"}</p></div><div className="rounded-2xl bg-gray-50 p-4"><ShieldCheck className="h-5 w-5 text-primary" /><p className="mt-2 text-xs text-gray-400">Offre</p><p className="font-semibold text-accent">{getPlanLabel(profile.plan)}</p></div></div></div></section><div className="mt-5 space-y-3"><button onClick={() => openWebPath(profile.role.includes("ADMIN") ? "/dashboard/settings" : profile.role === "TEACHER" ? "/teacher/settings" : "/parent")} className="flex w-full items-center justify-between rounded-2xl bg-white px-4 py-3 text-sm font-semibold text-accent shadow-sm"><span>Paramètres du compte</span><ExternalLink className="h-4 w-4 text-gray-400" /></button><button onClick={async () => { await signOut(); navigate("/auth/login", { replace: true }); }} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-red-100 bg-red-50 py-3 text-sm font-semibold text-red-600"><LogOut className="h-4 w-4" />Se déconnecter</button></div><div className="mt-10 flex items-center justify-center gap-2 text-xs text-gray-400">Propulsé par <ElimaLogo className="w-14" /></div></PageContainer>;
}
