create table if not exists public.revision_ai_quota_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('revision_generate', 'revision_document_analyze')),
  created_at timestamptz not null default now()
);

create index if not exists idx_revision_ai_quota_events_user_action_created
  on public.revision_ai_quota_events(user_id, action, created_at desc);

alter table public.revision_ai_quota_events enable row level security;
revoke all on table public.revision_ai_quota_events from public, anon, authenticated;
grant all on table public.revision_ai_quota_events to service_role;

create or replace function public.consume_revision_ai_quota(
  p_user_id uuid,
  p_action text,
  p_short_window_seconds integer,
  p_short_limit integer,
  p_daily_limit integer
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_short_since timestamptz;
  v_day_since timestamptz := v_now - interval '24 hours';
  v_short_count integer;
  v_daily_count integer;
  v_oldest timestamptz;
  v_retry_after integer;
begin
  if p_user_id is null
    or p_action not in ('revision_generate', 'revision_document_analyze')
    or p_short_window_seconds < 60
    or p_short_limit < 1
    or p_daily_limit < p_short_limit then
    raise exception 'Invalid quota policy';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_action, 0));
  v_short_since := v_now - make_interval(secs => p_short_window_seconds);

  select count(*) filter (where created_at >= v_short_since), count(*)
    into v_short_count, v_daily_count
  from public.revision_ai_quota_events
  where user_id = p_user_id and action = p_action and created_at >= v_day_since;

  if v_daily_count >= p_daily_limit then
    select min(created_at) into v_oldest
    from public.revision_ai_quota_events
    where user_id = p_user_id and action = p_action and created_at >= v_day_since;
    v_retry_after := greatest(1, ceil(extract(epoch from (v_oldest + interval '24 hours' - v_now)))::integer);
    return jsonb_build_object('allowed', false, 'scope', 'daily', 'retry_after', v_retry_after);
  end if;

  if v_short_count >= p_short_limit then
    select min(created_at) into v_oldest
    from public.revision_ai_quota_events
    where user_id = p_user_id and action = p_action and created_at >= v_short_since;
    v_retry_after := greatest(1, ceil(extract(epoch from (v_oldest + make_interval(secs => p_short_window_seconds) - v_now)))::integer);
    return jsonb_build_object('allowed', false, 'scope', 'short', 'retry_after', v_retry_after);
  end if;

  insert into public.revision_ai_quota_events(user_id, action) values (p_user_id, p_action);
  delete from public.revision_ai_quota_events
  where user_id = p_user_id and action = p_action and created_at < v_now - interval '48 hours';
  return jsonb_build_object('allowed', true, 'remaining_daily', p_daily_limit - v_daily_count - 1);
end;
$$;

revoke all on function public.consume_revision_ai_quota(uuid, text, integer, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_revision_ai_quota(uuid, text, integer, integer, integer) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'revision-document-uploads',
  'revision-document-uploads',
  false,
  10485760,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists revision_document_uploads_insert_own on storage.objects;
create policy revision_document_uploads_insert_own on storage.objects
for insert to authenticated
with check (
  bucket_id = 'revision-document-uploads'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists revision_document_uploads_select_own on storage.objects;
create policy revision_document_uploads_select_own on storage.objects
for select to authenticated
using (
  bucket_id = 'revision-document-uploads'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists revision_document_uploads_delete_own on storage.objects;
create policy revision_document_uploads_delete_own on storage.objects
for delete to authenticated
using (
  bucket_id = 'revision-document-uploads'
  and (storage.foldername(name))[1] = auth.uid()::text
);
